name: tunnel_forge
description: Tunnel Forge - L2TP/IPsec VPN for Android.
publish_to: "none"

version: 0.5.0+13

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^4.0.7
  bloc: ^9.0.0
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  get_it: ^8.2.0
  package_info_plus: ^8.3.1
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Estedad
      fonts:
        - asset: resources/fonts/estedad/Estedad-Thin.ttf
          weight: 100
        - asset: resources/fonts/estedad/Estedad-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/estedad/Estedad-Light.ttf
          weight: 300
        - asset: resources/fonts/estedad/Estedad-Regular.ttf
          weight: 400
        - asset: resources/fonts/estedad/Estedad-Medium.ttf
          weight: 500
        - asset: resources/fonts/estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/estedad/Estedad-Bold.ttf
          weight: 700
        - asset: resources/fonts/estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: resources/fonts/estedad/Estedad-Black.ttf
          weight: 900
